// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(2), // identifier
			shift(3), // boolean_t
			shift(4), // boolean_f
			shift(5), // number
			shift(6), // string
			shift(8), // (
			nil,      // )
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // identifier
			nil,          // boolean_t
			nil,          // boolean_f
			nil,          // number
			nil,          // string
			nil,          // (
			nil,          // )
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Value
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: Value
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: Value
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: Value
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: Value
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Value
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(10), // identifier
			shift(11), // boolean_t
			shift(12), // boolean_f
			shift(13), // number
			shift(14), // string
			shift(17), // (
			shift(18), // )
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(7), // identifier, reduce: ListElements
			reduce(7), // boolean_t, reduce: ListElements
			reduce(7), // boolean_f, reduce: ListElements
			reduce(7), // number, reduce: ListElements
			reduce(7), // string, reduce: ListElements
			reduce(7), // (, reduce: ListElements
			reduce(7), // ), reduce: ListElements
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(1), // identifier, reduce: Value
			reduce(1), // boolean_t, reduce: Value
			reduce(1), // boolean_f, reduce: Value
			reduce(1), // number, reduce: Value
			reduce(1), // string, reduce: Value
			reduce(1), // (, reduce: Value
			reduce(1), // ), reduce: Value
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(2), // identifier, reduce: Value
			reduce(2), // boolean_t, reduce: Value
			reduce(2), // boolean_f, reduce: Value
			reduce(2), // number, reduce: Value
			reduce(2), // string, reduce: Value
			reduce(2), // (, reduce: Value
			reduce(2), // ), reduce: Value
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(3), // identifier, reduce: Value
			reduce(3), // boolean_t, reduce: Value
			reduce(3), // boolean_f, reduce: Value
			reduce(3), // number, reduce: Value
			reduce(3), // string, reduce: Value
			reduce(3), // (, reduce: Value
			reduce(3), // ), reduce: Value
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(4), // identifier, reduce: Value
			reduce(4), // boolean_t, reduce: Value
			reduce(4), // boolean_f, reduce: Value
			reduce(4), // number, reduce: Value
			reduce(4), // string, reduce: Value
			reduce(4), // (, reduce: Value
			reduce(4), // ), reduce: Value
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(5), // identifier, reduce: Value
			reduce(5), // boolean_t, reduce: Value
			reduce(5), // boolean_f, reduce: Value
			reduce(5), // number, reduce: Value
			reduce(5), // string, reduce: Value
			reduce(5), // (, reduce: Value
			reduce(5), // ), reduce: Value
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(6), // identifier, reduce: Value
			reduce(6), // boolean_t, reduce: Value
			reduce(6), // boolean_f, reduce: Value
			reduce(6), // number, reduce: Value
			reduce(6), // string, reduce: Value
			reduce(6), // (, reduce: Value
			reduce(6), // ), reduce: Value
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(10), // identifier
			shift(11), // boolean_t
			shift(12), // boolean_f
			shift(13), // number
			shift(14), // string
			shift(17), // (
			shift(20), // )
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(10), // identifier
			shift(11), // boolean_t
			shift(12), // boolean_f
			shift(13), // number
			shift(14), // string
			shift(17), // (
			shift(22), // )
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // $, reduce: List
			nil,        // identifier
			nil,        // boolean_t
			nil,        // boolean_f
			nil,        // number
			nil,        // string
			nil,        // (
			nil,        // )
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(8), // identifier, reduce: ListElements
			reduce(8), // boolean_t, reduce: ListElements
			reduce(8), // boolean_f, reduce: ListElements
			reduce(8), // number, reduce: ListElements
			reduce(8), // string, reduce: ListElements
			reduce(8), // (, reduce: ListElements
			reduce(8), // ), reduce: ListElements
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // $, reduce: List
			nil,       // identifier
			nil,       // boolean_t
			nil,       // boolean_f
			nil,       // number
			nil,       // string
			nil,       // (
			nil,       // )
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(10), // identifier
			shift(11), // boolean_t
			shift(12), // boolean_f
			shift(13), // number
			shift(14), // string
			shift(17), // (
			shift(23), // )
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			reduce(10), // identifier, reduce: List
			reduce(10), // boolean_t, reduce: List
			reduce(10), // boolean_f, reduce: List
			reduce(10), // number, reduce: List
			reduce(10), // string, reduce: List
			reduce(10), // (, reduce: List
			reduce(10), // ), reduce: List
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(9), // identifier, reduce: List
			reduce(9), // boolean_t, reduce: List
			reduce(9), // boolean_f, reduce: List
			reduce(9), // number, reduce: List
			reduce(9), // string, reduce: List
			reduce(9), // (, reduce: List
			reduce(9), // ), reduce: List
		},
	},
}
