// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Value
		-1, // ListElements
		9,  // List
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S10
		-1, // S'
		12, // Value
		21, // ListElements
		20, // List
	},
	gotoRow{ // S11
		-1, // S'
		12, // Value
		25, // ListElements
		20, // List
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S21
		-1, // S'
		27, // Value
		-1, // ListElements
		20, // List
	},
	gotoRow{ // S22
		-1, // S'
		12, // Value
		29, // ListElements
		20, // List
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S24
		-1, // S'
		12, // Value
		31, // ListElements
		20, // List
	},
	gotoRow{ // S25
		-1, // S'
		27, // Value
		-1, // ListElements
		20, // List
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S29
		-1, // S'
		27, // Value
		-1, // ListElements
		20, // List
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S31
		-1, // S'
		27, // Value
		-1, // ListElements
		20, // List
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S33
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Value
		-1, // ListElements
		-1, // List
	},
}
